version: 1.0.{build}

branches:
  only:
    - master

configuration: Release

before_build:
  - nuget restore

build:
      project: MemoryDbSet\MemoryDbSet.csproj
      verbosity: minimal      
      publish_nuget: true
      include_nuget_references: true

deploy:
  - provider: NuGet
    api_key:
      secure: VMmYNhMOvK7DxZOKna0yOYRLtBWqyuBQSPD08mRIz70v9G//tAVOBbk+voQmltnJ
    artifact: /.*\.nupkg/

artifacts:
  path: MemoryDbSet\bin\$(configuration)
  name: MemoryDbSet
